//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_estacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bus_estacion()
        {
            this.bus_orden_linea = new HashSet<bus_orden_linea>();
        }
    
        public int CODIGOESTACION { get; set; }
        public Nullable<int> CODIGOPARADA { get; set; }
        public string DENOMINACION { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bus_orden_linea> bus_orden_linea { get; set; }
    }
}
