//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligero_orden_linea
    {
        public int FID { get; set; }
        public string NUMEROLINEAUSUARIO { get; set; }
        public int SENTIDO { get; set; }
        public int CODIGOESTACION { get; set; }
        public int NUMEROORDEN { get; set; }
        public string DENOMINACION { get; set; }
        public byte CODIGOPROVINCIA { get; set; }
        public byte CODIGOMUNICIPIO { get; set; }
        public string MUNICIPIO { get; set; }
        public double LONGITUDTRAMOANTERIOR { get; set; }
        public byte VELOCIDADTRAMOANTERIOR { get; set; }
    
        public virtual ligero_estacion ligero_estacion { get; set; }
    }
}
