//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class metro_estacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public metro_estacion()
        {
            this.metro_orden_linea = new HashSet<metro_orden_linea>();
            this.transbordos_ferroviarios = new HashSet<transbordos_ferroviarios>();
        }
    
        public int CODIGOESTACION { get; set; }
        public Nullable<int> CODIGOCTMESTACIONREDMETRO { get; set; }
        public string DENOMINACION { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metro_orden_linea> metro_orden_linea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transbordos_ferroviarios> transbordos_ferroviarios { get; set; }
    }
}
