//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class metro_tramo
    {
        public int id { get; set; }
        public Nullable<int> CODIGOESTACION { get; set; }
        public string NUMEROLINEAUSUARIO { get; set; }
        public Nullable<int> SENTIDO { get; set; }
    
        public virtual metro_estacion metro_estacion { get; set; }
    }
}
