//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class metro_orden_linea
    {
        public short OBJECTID { get; set; }
        public string NUMEROLINEAUSUARIO { get; set; }
        public byte SENTIDO { get; set; }
        public int CODIGOESTACION { get; set; }
        public byte NUMEROORDEN { get; set; }
        public string DENOMINACION { get; set; }
        public string MUNICIPIO { get; set; }
        public string DIRECCION { get; set; }
    
        public virtual metro_estacion metro_estacion { get; set; }
    }
}
