//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transbordos_ferroviarios
    {
        public int ID { get; set; }
        public Nullable<int> CEMetro { get; set; }
        public Nullable<int> CECercanias { get; set; }
        public Nullable<int> CELigero { get; set; }
    
        public virtual cercanias_estacion cercanias_estacion { get; set; }
        public virtual ligero_estacion ligero_estacion { get; set; }
        public virtual metro_estacion metro_estacion { get; set; }
    }
}
